version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "policyAutomatorTestOh"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1wra2jxbz3nim"
s3_prefix = "policyAutomatorTestOh"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "EmailAddress=\"benjasl@amazon.com\" restrictedActions=\"s3:DeleteBucket,s3:DeleteObject\""
